version: '3'
services:
  postgres:
    image: postgres:latest
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: Blog-Application
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    networks:
      - local

  keycloak:
    image: quay.io/keycloak/keycloak:25.0.0
    command: start-dev
    restart: always
    ports:
      - "9095:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin@1234
      KC_DB: postgres
      KC_DB_SCHEMA: public
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: password
      KC_DB_URL: jdbc:postgresql://postgres:5432/Blog-Application
      KC_HOSTNAME: localhost
      KC_FEATURES: token-exchange,admin-fine-grained-authz
    networks:
      - local

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bloggr-backend
    restart: always
    depends_on:
      - postgres
      - keycloak
    ports:
      - "8081:8083"

    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/Blog-Application
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
      KEYCLOAK_AUTH_SERVER_URL: http://keycloak:9082
    networks:
      - local

networks:
  local:

volumes:
  postgres_data:
