
app:
  keycloak:
    admin:
      clientId: identity
      clientSecret: hqmU0o2rN5K5aDf0vwRXXGNBidG9Kz4R
    realm: UserIdentity
    serverUrl: http://localhost:9082
    tokenUrl: http://localhost:9082/realms/UserIdentity/protocol/openid-connect/token

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9082/realms/UserIdentity
          jwk-set-uri: http://localhost:8080/realms/UserIdentity/protocol/openid-connect/certs
server:
  port: 8081
  servlet:
    context-path: /auth