KEYCLOAK_CLIENT_ID=identity
KEYCLOAK_CLIENT_SECRET=zyvcLJL6b3OVefAHT0CSmclYqK0A1H4e
KEYCLOAK_REALM=UserIdentity
KEYCLOAK_SERVER_URL=http://localhost:9085
KEYCLOAK_TOKEN_URL=http://localhost:9085/realms/UserIdentity/protocol/openid-connect/token
KEYCLOAK_LOGOUT_URL=http://localhost:9085/realms/UserIdentity/protocol/openid-connect/logout
KEYCLOAK_ISSUER_URI=http://localhost:9085/realms/UserIdentity
KEYCLOAK_JWK_SET_URI=http://localhost:9085/realms/UserIdentity/protocol/openid-connect/certs
DB_URL=jdbc:postgresql://localhost:5432/Blog-Application
DB_USER=postgres
DB_PASS=password